### ISSUE TITLE
GNU Modula2 backend

### ISSUE THREAD

**Issue by jpgpng** [modula3/cm3#1042]
GNU Modula-2 (gm2) is a decent compiler. It's in the process of being included as part of the GCC tree. Instead of only generate C we could try generating Modula-2 instead. We then utilize gm2 to generate the final binaries like the way gcc and g++ were used.

Here is gm2: https://www.nongnu.org/gm2/download.html

**Comment by VictorMiasnikov** [comment]
> GNU Modula-2 (gm2) is a decent compiler. It's in the process of being included as part of the GCC tree. Instead of only generate C we could try generating Modula-2 instead. We then utilize gm2 to generate the final binaries like the way gcc and g++ were used.
> 
> Here is gm2: https://www.nongnu.org/gm2/download.html

GNU Modula-2 (gm2) have support excpition handles, OS Windows ( .pdb for debuggers) and(or) #line directive? 


```
....
      EXCEPT
 . . .    FloatMode.Trap(fl) =>
....






...
      TRY
	BEGIN
	  x := one/zero;
	  x := -1.0;
	  s := 0;
	  r := 10;
	  r := r DIV s;
	  Wr.PutText (stderr, "** no trap\n");
	END;
      EXCEPT
	<* NOWARN *> FloatMode.Trap(fl) =>
	  BCheck("right flag ?", fl = Flag.IntDivByZero, TRUE);
	  Check("right value ?", x, -1.0);
      END;
...



...
#define	    FPE_INTDIV_TRAP	0x14	/* integer divide by zero */
...
 +
...
#define	    FPE_FLTDIV_TRAP	0xc8	/* [floating divide by zero] */
...
```


P.S.

>  Instead of only generate C we could try generating Modula-2 instead
I have related ideas. 

ToDo: add some URLs

**Comment by 3oheicrw** [comment]
@VictorMiasnikov GM2 is a GCC project so it's more in line with GCC and MinGW-W64. So, it will support the same thing as MinGW-W64 GCC. It definitely has exception handling, about pdb and `#line` directive I have no idea at all. You could reach the GM2 developer here, he's very respondsive: https://www.nongnu.org/gm2/12/community.html

IMO GM2 is a better backend than XDS, GM2 is actively developed and going to be merged into the GCC source tree.

**Comment by VictorMiasnikov** [comment]
> @VictorMiasnikov GM2 is a GCC project so it's more in line with GCC and MinGW-W64. So, it will support the same thing as MinGW-W64 GCC. It definitely has exception handling, about pdb and `#line` directive I have no idea at all. You could reach the GM2 developer here, he's very respondsive: https://www.nongnu.org/gm2/12/community.html
> 
> IMO GM2 is a better backend than XDS, GM2 is actively developed and going to be merged into the GCC source tree.

On any key there is "strategy" . . .

**Comment by jpgpng** [comment]
GNU Modula2 is more about Linux and Unix-like than Windows. Someone on the Modula2 mailing list (on Google Groups or gm2's own mailing list I don't remember) said they could have gm2 compiled and running under Cygwin. I personally never tried to get it working on Windows :disappointed:

**Comment by VictorMiasnikov** [comment]
As I known, modern version GNU Modula-2 does not work on Windows. Even inside MinGW.But Modula-3 wokrs.As result: GNU Modula-2 is "bad backend" for M3.P.S. Inside "my MinGW" You can found OO2C for x64.19.08.2022, 20:59, "jpgpng" ***@***.***>:
GNU Modula2 is more about Linux and Unix-like than Windows. Someone on the Modula2 mailing list (on Google Groups or gm2's own mailing list I don't remember) said they could have gm2 compiled and running under Cygwin. I personally never tried to get it working on Windows 😞

**Comment by VictorMiasnikov** [comment]
Cm3 AMD64_NT can create .dllCm3 AMD64_MINGW can not. First variant is better choice 19.08.2022, 20:59, "jpgpng" ***@***.***>:
GNU Modula2 is more about Linux and Unix-like than Windows. Someone on the Modula2 mailing list (on Google Groups or gm2's own mailing list I don't remember) said they could have gm2 compiled and running under Cygwin. I personally never tried to get it working on Windows 😞

**Comment by jpgpng** [comment]
I have really difficulty to parse the meanings of your messages. But, MinGW-W64 GCC has no problems making DLLs. If CM3 on AMD64_MINGW can't make DLLs then it's CM3's fault, you can't put your own limitation on MinGW-W64!

**Comment by jpgpng** [comment]
BTW, if a GNU Modula2 backend is not viable then I will close this issue.

**Comment by 3oheicrw** [comment]
Who said gm2 doesn't support Windows? It's going to be part of gcc as of gcc 13 and after that you could grab a ready to use gm2 for Windows from winlibs.com. See https://github.com/brechtsanders/winlibs_mingw/issues/110

**Comment by VictorMiasnikov** [comment]
Yes, this is cm3 AMD64_MINGW trouble.May be even temporary trouble 20.08.2022, 04:24, "jpgpng" ***@***.***>:
I have really difficulty to parse the meanings of your messages. But, MinGW-W64 GCC has no problems making DLLs. If CM3 on AMD64_MINGW can't make DLLs then it's CM3's fault, you can't put your own limitation on MinGW-W64!

**Comment by VictorMiasnikov** [comment]
May be vilable, I think we can reopen Issue 20.08.2022, 04:25, "jpgpng" ***@***.***>:
BTW, if a GNU Modula2 backend is not viable then I will close this issue.

**Comment by VictorMiasnikov** [comment]
It's a good news.20.08.2022, 05:18, "3oheicrw" ***@***.***>:
Who said gm2 doesn't support Windows? It's going to be part of gcc as of gcc 13 and after that you could grab a ready to use gm2 for Windows from winlibs.com. See brechtsanders/winlibs_mingw#110

**Comment by va0dl914** [comment]
I would suggest a Free Pascal backend. Windows is a second class citizen of GNU M2. GNU M2 is bloated. You will need a full GCC distro anyway (which will already included gcc and g++). Then why don't just use gcc and g++? GNU M2 is a good option if you started from scratch since the two languages have some similarity. But you already have C/C++ backend. There is no reasons for a GNU M2 backend.

**Comment by VictorMiasnikov** [comment]
To @pwd96m4a : Are You delete this msg?


> We are using gm2 on Linux for a while (we are using SparkyLinux aka Debian Testing, so it's available from the package manager by default). Today we will try to compile gm2 on Windows via both msys2 and cygwin and report back if we succeed. The same guide here for Linux could be followed: https://www.nongnu.org/gm2/11/building_on_gcc_11.html

**Comment by VictorMiasnikov** [comment]
> To @pwd96m4a : Are You delete this msg?
> 
> > We are using gm2 on Linux for a while (we are using SparkyLinux aka Debian Testing, so it's available from the package manager by default). Today we will try to compile gm2 on Windows via both msys2 and cygwin and report back if we succeed. The same guide here for Linux could be followed: https://www.nongnu.org/gm2/11/building_on_gcc_11.html

   I.e. after this we have answer on question:
 

>   You have already _successfully_ and good working GM2 Modula-2?

 I want remember: we need backend for all variants: AMD64_NT, AMD64_MINGW, AMD64_CYGWIN and theirs 32bit analogs

**Comment by pwd96m4a** [comment]
@VictorMiasnikov I can't clone the gm2 git repo. It seems the repo was moved. gm2 is on the process of migrating to the gcc source tree and this is not yet done. The build guide seems not updated. This is a mess right now.

**Comment by VictorMiasnikov** [comment]
> @VictorMiasnikov I can't clone the gm2 git repo. It seems the repo was moved. gm2 is on the process of migrating to the gcc source tree and this is not yet done. The build guide seems not updated. This is a mess right now.

Please, don't worry: this is "strategy issue"

**Comment by 3oheicrw** [comment]
Sorry everyone. I was wrong. GNU Modula-2 seems to be Unix-like only and will not work on Windows, even with Cygwin.

See https://github.com/brechtsanders/winlibs_mingw/issues/110

**Comment by VictorMiasnikov** [comment]
> Sorry everyone. I was wrong. GNU Modula-2 seems to be Unix-like only and will not work on Windows, even with Cygwin.
> 
> See [brechtsanders/winlibs_mingw#110](https://github.com/brechtsanders/winlibs_mingw/issues/110)

`+
`
> 
> Sorry everyone. I was wrong. GNU Modula-2 seems to be Unix-like only and will not work on Windows, even with Cygwin.
> 
> A few more details:
> 
> The repository the document used is now invalid: https://www.nongnu.org/gm2/11/building_on_gcc_11.html
> This mailing list discussion addressed it: https://lists.gnu.org/archive/html/gm2/2022-07/msg00008.html
> But it's not really, the repo at http://floppsie.comp.glam.ac.uk/git/gm2 is very unstable, it will stuck at 48% when cloning.
> 
> So everyone, we will clone from gcc's github mirror, the branch devel/modula-2:
> 
> git clone -b devel/modula-2 https://github.com/gcc-mirror/gcc gm2-floppsie
> 
> The configuration process is successfull but the actual building failed with no rules for target!
> 


Don't worry: I hope this is "temporary trouble".

In "other case" ( i.e. "it is permanent problem") we can use
XDS Oberon-2/Modula-2
 and ( or)
ADW Modula-2

**Comment by 3oheicrw** [comment]
> Don't worry: I hope this is "temporary trouble".

Developers of these projects (GNU Modula-2 and Vector Pascal Compiler and so on...) mostly run only Linux. It's easier for them to support other Unix-like OSes because these are very similar and if they didn't use so much Linuxism. Regarding Windows, I don't think it will change without a Windows specific contributor. In other words, they will happily merge the changes needed for Windows from that contributor, but they personally will do nothing about it. The growing in popular of WSL also eliminated the needs to support Windows. Why don't you have to support Windows if Windows now could run Linux binaries?

> In "other case" ( i.e. "it is permanent problem") we can use XDS Oberon-2/Modula-2 and ( or) ADW Modula-2

I don't see the point. ADW is closed source, Windows-only and there is absolutely no support from the developer. XDS generates C. So why don't improve the existing C backend instead? Or developing new backends, e.g: LLVM IR?

p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.

**Comment by 3oheicrw** [comment]
Err, he deleted his github account and I already forgot his account name. But his idea is more realistic, a Free Pascal backend, generates Pascal code and uses the Free Pascal compiler to compile.

**Comment by VictorMiasnikov** [comment]
> Err, he deleted his github account and I already forgot his account name. But his idea is more realistic, a Free Pascal backend, generates Pascal code and uses the Free Pascal compiler to compile.

May be: Free Pascal write that they "have more targets than" LLVM and this targets "are another t-s"

**Comment by VictorMiasnikov** [comment]
> > Don't worry: I hope this is "temporary trouble".
> 
> Developers of these projects (GNU Modula-2 and Vector Pascal Compiler and so on...) mostly run only Linux. It's easier for them to support other Unix-like OSes because these are very similar and if they didn't use so much Linuxism. Regarding Windows, I don't think it will change without a Windows specific contributor. In other words, they will happily merge the changes needed for Windows from that contributor, but they personally will do nothing about it. The growing in popular of WSL also eliminated the needs to support Windows. Why don't you have to support Windows if Windows now could run Linux binaries?
> 
> > In "other case" ( i.e. "it is permanent problem") we can use XDS Oberon-2/Modula-2 and ( or) ADW Modula-2
> 
> I don't see the point. ADW is closed source, Windows-only and there is absolutely no support from the developer. XDS generates C. So why don't improve the existing C backend instead? Or developing new backends, e.g: LLVM IR?
> 
> p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.



> he growing in popular of WSL also eliminated the needs to support Windows.

`2)` It is no "eliminated"
`1)` There is ReactOS ( "free Windows" Server 2003 32bit + x64)

**Comment by 3oheicrw** [comment]
> > Err, he deleted his github account and I already forgot his account name. But his idea is more realistic, a Free Pascal backend, generates Pascal code and uses the Free Pascal compiler to compile.
> 
> May be: Free Pascal write that they "have more targets than" LLVM and this targets "are another t-s"

Sorry, but I don't understand what you said. Yes, FPC (and GCC, of course), supports more targets (platforms or architectures to be more clear) than LLVM. It's a fact that everyone knows. But what does "are another t-s" means?

**Comment by 3oheicrw** [comment]
> > > Don't worry: I hope this is "temporary trouble".
> > 
> > 
> > Developers of these projects (GNU Modula-2 and Vector Pascal Compiler and so on...) mostly run only Linux. It's easier for them to support other Unix-like OSes because these are very similar and if they didn't use so much Linuxism. Regarding Windows, I don't think it will change without a Windows specific contributor. In other words, they will happily merge the changes needed for Windows from that contributor, but they personally will do nothing about it. The growing in popular of WSL also eliminated the needs to support Windows. Why don't you have to support Windows if Windows now could run Linux binaries?
> > > In "other case" ( i.e. "it is permanent problem") we can use XDS Oberon-2/Modula-2 and ( or) ADW Modula-2
> > 
> > 
> > I don't see the point. ADW is closed source, Windows-only and there is absolutely no support from the developer. XDS generates C. So why don't improve the existing C backend instead? Or developing new backends, e.g: LLVM IR?
> > p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.
> 
> > he growing in popular of WSL also eliminated the needs to support Windows.
> 
> `2)` It is no "eliminated" `1)` There is ReactOS ( "free Windows" Server 2003 32bit + x64)

ReactOS has nothing to do here. The developers of said project (gm2 and vpc) will definitely not use and test on ReactOS. Their development platform is Linux so Linux is the first class citizen here. Windows is the lowest tier for them.

> 
> P.S.
> 
> > XDS generates C.
> 
> XDS has 2 mode: first generates C, second - binaries, directly

I read about XDS very carefully. The binaries mode is Windows-only. To be able to build on Linux, the C mode has to be used.

> 
> P.P.S.
> 
> > Or developing new backends, e.g: LLVM IR?
> 
> We have it now ( / "already")
> 
> P.P.P.S.
> 
> > p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.
> 
> Please see [#1065 (comment)](https://github.com/modula3/cm3/issues/1065#issuecomment-1259429354)

I saw your reply.

**Comment by VictorMiasnikov** [comment]
IMHO, XDS Oberon-2/Modula-2 is most interesting as I386_NT optimized_ compiler _totally_ independent from mainstream C language "clones"27.09.2022, 21:22, "3oheicrw" ***@***.***>:



Don't worry: I hope this is "temporary trouble".

Developers of these projects (GNU Modula-2 and Vector Pascal Compiler and so on...) mostly run only Linux. It's easier for them to support other Unix-like OSes because these are very similar and if they didn't use so much Linuxism. Regarding Windows, I don't think it will change without a Windows specific contributor. In other words, they will happily merge the changes needed for Windows from that contributor, but they personally will do nothing about it. The growing in popular of WSL also eliminated the needs to support Windows. Why don't you have to support Windows if Windows now could run Linux binaries?

In "other case" ( i.e. "it is permanent problem") we can use XDS Oberon-2/Modula-2 and ( or) ADW Modula-2

I don't see the point. ADW is closed source, Windows-only and there is absolutely no support from the developer. XDS generates C. So why don't improve the existing C backend instead? Or developing new backends, e.g: LLVM IR?
p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.


he growing in popular of WSL also eliminated the needs to support Windows.

2) It is no "eliminated" 1) There is ReactOS ( "free Windows" Server 2003 32bit + x64)

ReactOS has nothing to do here. The developers of said project (gm2 and vpc) will definitely not use and test on ReactOS. Their development platform is Linux so Linux is the first class citizen here. Windows is the lowest tier for them.

P.S.

XDS generates C.

XDS has 2 mode: first generates C, second - binaries, directly

I read about XDS very carefully. The binaries mode is Windows-only. To be able to build on Linux, the C mode has to be used.

P.P.S.

Or developing new backends, e.g: LLVM IR?

We have it now ( / "already")
P.P.P.S.

p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.

Please see #1065 (comment)

I saw your reply.

**Comment by VictorMiasnikov** [comment]
P.S. ReactOs,  Windows 2003, Windows 7 don't have both WSL and Hyper-V based WSL2.P.P.S. Some Win32 compilers can produce code for MS DOS "with extender" HX27.09.2022, 21:22, "3oheicrw" ***@***.***>:



Don't worry: I hope this is "temporary trouble".

Developers of these projects (GNU Modula-2 and Vector Pascal Compiler and so on...) mostly run only Linux. It's easier for them to support other Unix-like OSes because these are very similar and if they didn't use so much Linuxism. Regarding Windows, I don't think it will change without a Windows specific contributor. In other words, they will happily merge the changes needed for Windows from that contributor, but they personally will do nothing about it. The growing in popular of WSL also eliminated the needs to support Windows. Why don't you have to support Windows if Windows now could run Linux binaries?

In "other case" ( i.e. "it is permanent problem") we can use XDS Oberon-2/Modula-2 and ( or) ADW Modula-2

I don't see the point. ADW is closed source, Windows-only and there is absolutely no support from the developer. XDS generates C. So why don't improve the existing C backend instead? Or developing new backends, e.g: LLVM IR?
p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.


he growing in popular of WSL also eliminated the needs to support Windows.

2) It is no "eliminated" 1) There is ReactOS ( "free Windows" Server 2003 32bit + x64)

ReactOS has nothing to do here. The developers of said project (gm2 and vpc) will definitely not use and test on ReactOS. Their development platform is Linux so Linux is the first class citizen here. Windows is the lowest tier for them.

P.S.

XDS generates C.

XDS has 2 mode: first generates C, second - binaries, directly

I read about XDS very carefully. The binaries mode is Windows-only. To be able to build on Linux, the C mode has to be used.

P.P.S.

Or developing new backends, e.g: LLVM IR?

We have it now ( / "already")
P.P.P.S.

p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.

Please see #1065 (comment)

I saw your reply.

**Comment by VictorMiasnikov** [comment]
T-s eq targets27.09.2022, 21:16, "3oheicrw" ***@***.***>:


Err, he deleted his github account and I already forgot his account name. But his idea is more realistic, a Free Pascal backend, generates Pascal code and uses the Free Pascal compiler to compile.

May be: Free Pascal write that they "have more targets than" LLVM and this targets "are another t-s"

Sorry, but I don't understand what you said. Yes, FPC (and GCC, of course), supports more targets (platforms or architectures to be more clear) than LLVM. It's a fact that everyone knows. But what does "are another t-s" means?

**Comment by 3oheicrw** [comment]
This is latest draft and still failed to build on Cygwin: https://splendidisolation.ddns.net/public/modula2/gm2patchset/readme.email It's better than the last time I tried, it could keep going for a while before ended up with an error.

**Comment by VictorMiasnikov** [comment]
Q: Are You will compile? Or You have already _successfully_ and good working GM2 Modula-2. I want remember: we need backend for all variants: AMD64_NT, AMD64_MINGW, AMD64_CYGWIN and theirs 32bit anologs07.09.2022, 04:16, "pwd96m4a" ***@***.***>:
We are using gm2 on Linux for a while (we are using SparkyLinux aka Debian Testing, so it's available from the package manager by default). Today we will try to compile gm2 on Windows via both msys2 and cygwin and report back if we succeed. The same guide here for Linux could be followed: https://www.nongnu.org/gm2/11/building_on_gcc_11.html

**Comment by VictorMiasnikov** [comment]
We do not have problems with Linux. Windows is main problem of "Modula-2 backend.27.09.2022, 21:22, "3oheicrw" ***@***.***>:



Don't worry: I hope this is "temporary trouble".

Developers of these projects (GNU Modula-2 and Vector Pascal Compiler and so on...) mostly run only Linux. It's easier for them to support other Unix-like OSes because these are very similar and if they didn't use so much Linuxism. Regarding Windows, I don't think it will change without a Windows specific contributor. In other words, they will happily merge the changes needed for Windows from that contributor, but they personally will do nothing about it. The growing in popular of WSL also eliminated the needs to support Windows. Why don't you have to support Windows if Windows now could run Linux binaries?

In "other case" ( i.e. "it is permanent problem") we can use XDS Oberon-2/Modula-2 and ( or) ADW Modula-2

I don't see the point. ADW is closed source, Windows-only and there is absolutely no support from the developer. XDS generates C. So why don't improve the existing C backend instead? Or developing new backends, e.g: LLVM IR?
p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.


he growing in popular of WSL also eliminated the needs to support Windows.

2) It is no "eliminated" 1) There is ReactOS ( "free Windows" Server 2003 32bit + x64)

ReactOS has nothing to do here. The developers of said project (gm2 and vpc) will definitely not use and test on ReactOS. Their development platform is Linux so Linux is the first class citizen here. Windows is the lowest tier for them.

P.S.

XDS generates C.

XDS has 2 mode: first generates C, second - binaries, directly

I read about XDS very carefully. The binaries mode is Windows-only. To be able to build on Linux, the C mode has to be used.

P.P.S.

Or developing new backends, e.g: LLVM IR?

We have it now ( / "already")
P.P.P.S.

p/s: BTW, is there any existing C++ backend? The compiled source file extension is .cpp but they are plain C.

Please see #1065 (comment)

I saw your reply.

**Comment by 3oheicrw** [comment]
https://gcc.gnu.org/pipermail/gcc-patches/2022-October/603161.html

**Comment by VictorMiasnikov** [comment]
>> 08.09.2022, 08:45 VVM Say: I.e. 1) "old repo" killed / deleted 2) and inside "big GCC repo" GM2 doesn't exist?
>
> https://gcc.gnu.org/pipermail/gcc-patches/2022-October/603161.html
> = = 
>[PATCH] 0/19 modula-2 front end patches overview
> = = 

 Thank You!
