### ISSUE TITLE
Cygwin gcc new issues (threads related)

### ISSUE THREAD

**Issue by jpgpng** [modula3/cm3#1055]
As we already known it's the Cygwin's version of cmake that caused problems in https://github.com/modula3/cm3/issues/1054 we now try using the same procedure as https://github.com/modula3/cm3/issues/1054 to build with Cygwin gcc, except the environment variables will be like this:

```
set CC=x86_64-pc-cygwin-gcc
set CXX=x86_64-pc-cygwin-g++
```

and the target will be `AMD64_CYGWIN` instead of `AMD64_MINGW`.

cmake told us that the variables `COMCTL32`, `IPHLPAPI` and `WS2_32` are set to `NOTFOUND`.

First I tried to pass `-DCMAKE_PREFIX_PATH=C:/cygwin64/lib/w32api` but it doesn't work. So finally I have to edit `bootstrap.cmake` directly and make dirty hacks like this:

```
# Find required system libraries for Windows builds.
if(WIN32)
   #find_library(COMCTL32 comctl32 REQUIRED)
   #find_library(IPHLPAPI iphlpapi REQUIRED)
   #find_library(WS2_32   ws2_32   REQUIRED)
   set(COMCTL32 "C:/cygwin64/lib/w32api/libcomctl32.a")
   set(IPHLPAPI "C:/cygwin64/lib/w32api/libiphlpapi.a")
   set(WS2_32 "C:/cygwin64/lib/w32api/libws2_32.a")
   set(win32_libs "${COMCTL32}" "${IPHLPAPI}" "${WS2_32}" Threads)
endif()
```

The hacks worked. Except we are still in linking errors. Now it's something about threads. I suggest you try this procedure and figure it out yourself @VictorMiasnikov as I will not try any further. I instead want to drop the `AMD64_CYGWIN` target. @jaykrell Do you agree with me about dropping `AMD64_CYGWIN`?

**Comment by VictorMiasnikov** [comment]
Cm3 AMD64_CYGWIN is useful I do _not_ agree kill it( There is again "smartphone style")06.09.2022, 07:55, "jpgpng" ***@***.***>:
As we already known it's the Cygwin's version of cmake that caused problems in #1054 we now try using the same procedure as #1054 to build with Cygwin gcc, except the environment variables will be like this:
set CC=x86_64-pc-cygwin-gcc
set CXX=x86_64-pc-cygwin-g++

and the target will be AMD64_CYGWIN instead of AMD64_MINGW.
cmake told us that the variables COMCTL32, IPHLPAPI and WS2_32 are set to NOTFOUND.
First I tried to pass -DCMAKE_PREFIX_PATH=C:/cygwin64/lib/w32api but it doesn't work. So finally I have to edit bootstrap.cmake directly and make dirty hacks like this:
# Find required system libraries for Windows builds.
if(WIN32)
   #find_library(COMCTL32 comctl32 REQUIRED)
   #find_library(IPHLPAPI iphlpapi REQUIRED)
   #find_library(WS2_32   ws2_32   REQUIRED)
   set(COMCTL32 "C:/cygwin64/lib/w32api/libcomctl32.a")
   set(IPHLPAPI "C:/cygwin64/lib/w32api/libiphlpapi.a")
   set(WS2_32 "C:/cygwin64/lib/w32api/libws2_32.a")
   set(win32_libs "${COMCTL32}" "${IPHLPAPI}" "${WS2_32}" Threads)
endif()

The hacks worked. Except we are still in linking errors. Now it's something about threads. I suggest you try this procedure and figure it out yourself @VictorMiasnikov as I will not try any further. I instead want to drop the AMD64_CYGWIN target. @jaykrell Do you agree with me about dropping AMD64_CYGWIN?

**Comment by jpgpng** [comment]
> Cm3 AMD64_CYGWIN is useful I do _not_ agree kill it( There is again "smartphone style")

Then please help with the new linking issues. It's something about threads. I don't know anything about cm3's code so it's up to you. I think going with cmake like me is better than edit manually and build one by one like you are doing on https://github.com/modula3/cm3/issues/1052

**Comment by VictorMiasnikov** [comment]
> > Cm3 AMD64_CYGWIN is useful I do _not_ agree kill it( There is again "smartphone style")
> 
> Then please help with the new linking issues. It's something about threads. I don't know anything about cm3's code so it's up to you. I think going with cmake like me is better than edit manually and build one by one like you are doing on #1052

One sec . . .

It looks like Github "kill" my Message N2 . . .

**Comment by VictorMiasnikov** [comment]
> As we already known it's the Cygwin's version of cmake that caused problems in #1054 we now try using the same procedure as #1054 to build with Cygwin gcc, except the environment variables will be like this:
> 
> ```
> set CC=x86_64-pc-cygwin-gcc
> set CXX=x86_64-pc-cygwin-g++
> ```
> 
> and the target will be `AMD64_CYGWIN` instead of `AMD64_MINGW`.
> 
> cmake told us that the variables `COMCTL32`, `IPHLPAPI` and `WS2_32` are set to `NOTFOUND`.
> 
> First I tried to pass `-DCMAKE_PREFIX_PATH=C:/cygwin64/lib/w32api` but it doesn't work. So finally I have to edit `bootstrap.cmake` directly and make dirty hacks like this:
> 
> ```
> # Find required system libraries for Windows builds.
> if(WIN32)
>    #find_library(COMCTL32 comctl32 REQUIRED)
>    #find_library(IPHLPAPI iphlpapi REQUIRED)
>    #find_library(WS2_32   ws2_32   REQUIRED)
>    set(COMCTL32 "C:/cygwin64/lib/w32api/libcomctl32.a")
>    set(IPHLPAPI "C:/cygwin64/lib/w32api/libiphlpapi.a")
>    set(WS2_32 "C:/cygwin64/lib/w32api/libws2_32.a")
>    set(win32_libs "${COMCTL32}" "${IPHLPAPI}" "${WS2_32}" Threads)
> endif()
> ```
> 
> The hacks worked. Except we are still in linking errors. Now it's something about threads. I suggest you try this procedure and figure it out yourself @VictorMiasnikov as I will not try any further. I instead want to drop the `AMD64_CYGWIN` target. @jaykrell Do you agree with me about dropping `AMD64_CYGWIN`?


"Cmake .py" is alternative.


 Part 1:

Then it works - it is good.

If it doesn't work then use "boot1.py --} make --} boot2.py" "methodology".


 Part 2:

ToDo

**Comment by jpgpng** [comment]
The only thing I know is the cmake based build script and I will always prefer it as cmake doesn't need any kind of posix environment like autotools. But this issue is about Cygwin, a posix environment, so if autotools works better then just use it.

**Comment by VictorMiasnikov** [comment]
"Cmake .py" is alternative.Then it works - it is good.If it doesn't work then use "boot1.py --} make --} boot2.py" "methodology".06.09.2022, 07:55, "jpgpng" ***@***.***>:
As we already known it's the Cygwin's version of cmake that caused problems in #1054 we now try using the same procedure as #1054 to build with Cygwin gcc, except the environment variables will be like this:
set CC=x86_64-pc-cygwin-gcc
set CXX=x86_64-pc-cygwin-g++

and the target will be AMD64_CYGWIN instead of AMD64_MINGW.
cmake told us that the variables COMCTL32, IPHLPAPI and WS2_32 are set to NOTFOUND.
First I tried to pass -DCMAKE_PREFIX_PATH=C:/cygwin64/lib/w32api but it doesn't work. So finally I have to edit bootstrap.cmake directly and make dirty hacks like this:
# Find required system libraries for Windows builds.
if(WIN32)
   #find_library(COMCTL32 comctl32 REQUIRED)
   #find_library(IPHLPAPI iphlpapi REQUIRED)
   #find_library(WS2_32   ws2_32   REQUIRED)
   set(COMCTL32 "C:/cygwin64/lib/w32api/libcomctl32.a")
   set(IPHLPAPI "C:/cygwin64/lib/w32api/libiphlpapi.a")
   set(WS2_32 "C:/cygwin64/lib/w32api/libws2_32.a")
   set(win32_libs "${COMCTL32}" "${IPHLPAPI}" "${WS2_32}" Threads)
endif()

The hacks worked. Except we are still in linking errors. Now it's something about threads. I suggest you try this procedure and figure it out yourself @VictorMiasnikov as I will not try any further. I instead want to drop the AMD64_CYGWIN target. @jaykrell Do you agree with me about dropping AMD64_CYGWIN?

**Comment by VictorMiasnikov** [comment]
Issue's solved: please, see https://github.com/modula3/cm3/issues/1052#issuecomment-1240900784

(

> mini-HowTo

 0`)` Unpack source code to /usr/local/cm3/src/
 1`)` Download file
cm3-boot-AMD64_CYGWIN-d5.11.9-CYGWIN64-2022-02-08_13-48__FIXed__by__VVM__20220906_15-57__16bit__Unicode__AMD64_CYGWIN__Target__cm3-69f22c9.7z
(

https://github.com/VictorMiasnikov/cm3/releases/download/d5.11.9-ZZYYXX-20220208_13-48/cm3-boot-AMD64_CYGWIN-d5.11.9-CYGWIN64-2022-02-08_13-48__FIXed__by__VVM__20220906_15-57__16bit__Unicode__AMD64_CYGWIN__Target__cm3-69f22c9.7z

)

 2`)` Unpack to any folder, run make
 3`)` Copy resulted cm3.exe to folder /usr/local/cm3/bin
 4`)` Run:

export PATH=/usr/local/cm3/bin:$PATH
cd /usr/local/cm3/src/scripts/python/
python boot2.py AMD64_CYGWIN


)
