### ISSUE TITLE
Windows API headers are outdated?

### ISSUE THREAD

**Issue by pwd96m4a** [modula3/cm3#1062]
Is there any plans to update them to contemporary versions?

**Comment by VictorMiasnikov** [comment]
> Windows API headers are outdated

May be.  You can try use m3swig[.exe] utility

**Comment by pwd96m4a** [comment]
> > Windows API headers are outdated
> 
> May be. You can try use m3swig[.exe] utility

This is something the developers should do, not the users.

**Comment by VictorMiasnikov** [comment]
Why? We have big runtime insidd m3lib and m3core.What You want implement on low-level API?08.09.2022, 20:04, "pwd96m4a" ***@***.***>:


Windows API headers are outdated

May be. You can try use m3swig[.exe] utility

This is something the developers should do, not the users.

**Comment by pwd96m4a** [comment]
> Why? We have big runtime insidd m3lib and m3core.What You want implement on low-level API?

Windows API is the way you talk with Windows OS. Don't be confused as Windows API is not only about GUI. Think about this: you want to use Windows' Shadow Copy service to make a shadow copy of the C drive running Windows itself in order to backup it to a drive image. How could you do this without using the Windows API? Don't count .NET framework and Microsoft already wrapped the Windows API to be ready to use API on .NET.

**Comment by VictorMiasnikov** [comment]
(> } Windows' Shadow CopyI know it as "WSS" or VSS. I don't remember exactly )I read "cm3 discussion(s)" on Github.It contains good answers. It good.It doesn't contain "m3swig". It's strange...09.09.2022, 12:11, "pwd96m4a" ***@***.***>:

Why? We have big runtime insidd m3lib and m3core.What You want implement on low-level API?

Windows API is the way you talk with Windows OS. Don't be confused as Windows API is not only about GUI. Think about this: you want to use Windows' Shadow Copy service to make a shadow copy of the C drive running Windows itself in order to backup it to a drive image. How could you do this without using the Windows API? Don't count .NET framework and Microsoft already wrapped the Windows API to be ready to use API on .NET.
