### ISSUE TITLE
IR changed

### ISSUE THREAD

**Issue by demoitem** [modula3/cm3#210]
Since the packed vars branch was merged I have noticed a slight IR change to do with temps. I mentioned this
to Rodney in an email but thought I would produce a small example.

This program
MODULE Main;

PROCEDURE Test8() : CHAR =
  BEGIN
    RETURN VAL(65,CHAR);
  END Test8;

PROCEDURE TestIt() =
  VAR i8 : CHAR;
  BEGIN
    i8 := Test8();
  END TestIt;

BEGIN
  TestIt();
END Main.

produces the following (snipped) IR

...
	declare_procedure	 Main__Test8 0 Word.8 0 0 F * p.4         <----- declared return type Word.8 ie 8 bit Word
	declare_local	 _result 1 1 Word.8 1457612899 F F 50 v.4   <---- result type Word.8 not used
	declare_procedure	 Main__TestIt 0 Void 0 0 F * p.5
	declare_local	 i8 1 1 Word.8 1457612899 F F 50 v.5
	# Test8
					-----LINE 3  -----
	begin_procedure	 p.4
	import_procedure	 alloca 1 Addr 0 p.6
	declare_param	 * 8 8 Word.64 0 F F 0 v.6
	import_global	 m3_jmpbuf_size 8 8 Word.64 0 v.7
	# AllocateJmpbufs Test8 try_count:0
					-----LINE 4  -----
					-----LINE 5  -----
	load_integer	 Int.64 65
	exit_proc	 Word.64                                 <---- Not exactly relevant to the issue but shouldn't this agree with the return type?
	end_procedure	 p.4
	# TestIt
					-----LINE 8  -----
	begin_procedure	 p.5
	# AllocateJmpbufs TestIt try_count:0
					-----LINE 9  -----
					-----LINE 11  -----
	start_call_direct	 p.4 0 Word.8
	call_direct	 p.4 Word.8                    <----- Again return type Word.8
	declare_temp	 8 8 Int.64 F v.8             <----- Problem - temp (for func result) is declared Int.64 whereas it used to be Word.8
	store		 v.8 0 Int.64 Int.64         <----- Store result of func on stack (which is Word.8) into Int.64 v.8 temp
	load		 v.8 0 Int.64 Int.64                  <----- Load has same problem
	store		 v.5 0 Int.64 Word.8
					-----LINE 12  -----
	exit_proc	 Void
	free_temp	 v.8
	end_procedure	 p.5
...

And it generates bad code like this in LLVM
  %tmp.16 = alloca i64, align 8
.....
  %result1 = call i8 @Main__Test8()
  store i8 %result1, i64* %tmp.16, align 1    <--- where the %tmp.16 is the wrong size it should be i8*

We could possibly fix this in the llvm store() function by checking the size of the value
on the stack and doing a trunc. But that sort of defeats the purpose of the type parameters
and the fact is it used to work.

**Comment by RodneyBates** [comment]
How far back did it used to work?  I get the same output from a head compiler
compiled on Aug 19, 2018.  I'll look for something earlier to try.

On 3/18/21 1:23 AM, peter mckinna wrote:
> Since the packed vars branch was merged I have noticed a slight IR change to do with temps. I mentioned this
> to Rodney in an email but thought I would produce a small example.
> 
> This program
> MODULE Main;
> 
> PROCEDURE Test8() : CHAR =
> BEGIN
> RETURN VAL(65,CHAR);
> END Test8;
> 
> PROCEDURE TestIt() =
> VAR i8 : CHAR;
> BEGIN
> i8 := Test8();
> END TestIt;
> 
> BEGIN
> TestIt();
> END Main.
> 
> produces the following (snipped) IR
> 
> ...
> declare_procedure Main__Test8 0 Word.8 0 0 F * p.4 <----- declared return type Word.8 ie 8 bit Word
> declare_local _result 1 1 Word.8 1457612899 F F 50 v.4 <---- result type Word.8 not used
> declare_procedure Main__TestIt 0 Void 0 0 F * p.5
> declare_local i8 1 1 Word.8 1457612899 F F 50 v.5
> # Test8
> -----LINE 3 -----
> begin_procedure p.4
> import_procedure alloca 1 Addr 0 p.6
> declare_param * 8 8 Word.64 0 F F 0 v.6
> import_global m3_jmpbuf_size 8 8 Word.64 0 v.7
> # AllocateJmpbufs Test8 try_count:0
> -----LINE 4 -----
> -----LINE 5 -----
> load_integer Int.64 65
> exit_proc Word.64 <---- Not exactly relevant to the issue but shouldn't this agree with the return type?
> end_procedure p.4
> # TestIt
> -----LINE 8 -----
> begin_procedure p.5
> # AllocateJmpbufs TestIt try_count:0
> -----LINE 9 -----
> -----LINE 11 -----
> start_call_direct p.4 0 Word.8
> call_direct p.4 Word.8 <----- Again return type Word.8
> declare_temp 8 8 Int.64 F v.8 <----- Problem - temp (for func result) is declared Int.64 whereas it used to be Word.8
> store v.8 0 Int.64 Int.64 <----- Store result of func on stack (which is Word.8) into Int.64 v.8 temp

The temp''s being Int.64 should work, if the store were
   store v.8 0 Word.8 Int.64

**Comment by RodneyBates** [comment]
I used a 5.8.6 executable compiler (also required a different m3cgcat and
found some differences.  I'm not sure what needs to be done, but here's
what is happening:

On 3/18/21 1:23 AM, peter mckinna wrote:
> Since the packed vars branch was merged I have noticed a slight IR change to do with temps. I mentioned this
> to Rodney in an email but thought I would produce a small example.
> 
> This program
> MODULE Main;
> 
> PROCEDURE Test8() : CHAR =
> BEGIN
> RETURN VAL(65,CHAR);
> END Test8;
> 
> PROCEDURE TestIt() =
> VAR i8 : CHAR;
> BEGIN
> i8 := Test8();
> END TestIt;
> 
> BEGIN
> TestIt();
> END Main.
> 
> produces the following (snipped) IR
> 
> ...
> declare_procedure Main__Test8 0 Word.8 0 0 F * p.4 <----- declared return type Word.8 ie 8 bit Word

Noted.

> declare_local _result 1 1 Word.8 1457612899 F F 50 v.4 <---- result type Word.8 not used
> declare_procedure Main__TestIt 0 Void 0 0 F * p.5
> declare_local i8 1 1 Word.8 1457612899 F F 50 v.5
> # Test8
> -----LINE 3 -----
> begin_procedure p.4
> import_procedure alloca 1 Addr 0 p.6
> declare_param * 8 8 Word.64 0 F F 0 v.6
> import_global m3_jmpbuf_size 8 8 Word.64 0 v.7
> # AllocateJmpbufs Test8 try_count:0
> -----LINE 4 -----
> -----LINE 5 -----
> load_integer Int.64 65
> exit_proc Word.64 <---- Not exactly relevant to the issue but shouldn't this agree with the return type?

I think it is relevant, but for this example, only in an indirect way.
The type returned here and the type the call site assumes should agree
with each other, but IR should be able to return in a 64, so long as
declare_procedure and exit_proc agree.

But they disagree on signedness.  This has not changed.  It probably
doesn't matter in this example, because the value is within the overlap
of signed and unsigned interpretation, so just redesignating it would
work, for generated code. But in general, it is wrong.

As for the 8 vs. 64 size disagreement between declare_procedure and
exit_proc, I think, in earlier back ends, the type in the declare_procedure
may be used only to produce debug info.  Still, I would expect this to
undermine the ability of a debugger to make a call on the function.


> end_procedure p.4
> # TestIt
> -----LINE 8 -----
> begin_procedure p.5
> # AllocateJmpbufs TestIt try_count:0
> -----LINE 9 -----
> -----LINE 11 -----
> start_call_direct p.4 0 Word.8
> call_direct p.4 Word.8 <----- Again return type Word.8
> declare_temp 8 8 Int.64 F v.8 <----- Problem - temp (for func result) is declared Int.64 whereas it used to be Word.8
> store v.8 0 Int.64 Int.64 <----- Store result of func on stack (which is Word.8) into Int.64 v.8 temp
               ^ It was Word.64, on the stack, as returned by the function.
                      ^ This agrees with the temp v.8.

> load v.8 0 Int.64 Int.64 <----- Load has same problem
> store v.5 0 Int.64 Word.8

The old code:
        --LINE 11  -----
	start_call_direct	 p.4 0 Word.8
	call_direct	 p.4 Word.8
	declare_temp	 1 1 Word.8 F v.6
	store		 v.6 0 Int.64 Word.8
	load		 v.6 0 Word.8 Int.64
	store		 v.5 0 Int.64 Word.8

Also disagrees with stack type of result.  But the temp is Word.8.
Correctly converts the stack result when storing into the temp.
Then reloads to stack, converting back to Int.64, then stores
into the declared local variable, converting again to Word.8.
This is certainly overly pedantic.  This is where the IR has changed.



> -----LINE 12 -----
> exit_proc Void
> free_temp v.8
> end_procedure p.5
> ...
> 
> And it generates bad code like this in LLVM
> %tmp.16 = alloca i64, align 8
> .....
> %result1 = call i8 @Main__Test8()
> store i8 %result1, i64* %tmp.16, align 1 <--- where the %tmp.16 is the wrong size it should be i8*

I'm guessing the production of the llvm store took the size from the declare_procedure,
disagreeing with the now-64-bit temp.

So what to do?  Certainly, the the exit_proc, IR store after the call, and the llvm store
have to agree.  The temp and the loads and stores of it have to agree, but I think
the front end should have the freedom to make this different.  And the debug info
needs to be checked and maybe fixed.

> 
> We could possibly fix this in the llvm store() function by checking the size of the value

Let's keep fingers out of llvm itself.  out-of-llvm-tree modifications introduce a big
new set of maintenance problems.

**Comment by demoitem** [comment]
I checked with my old build which I think was November last year. Pretty
sure
it was up to date then

 # AllocateJmpbufs TestIt try_count:0
-----LINE 15  -----
-----LINE 20  -----
start_call_direct p.4 0 Word.8
call_direct p.4 Word.8
declare_temp 1 1 Word.8 F v.9
store v.9 0 Int.64 Word.8
load v.9 0 Word.8 Int.64
store v.6 0 Int.64 Word.8
-----LINE 25  -----

As you can see the temp is 1 byte in size.

I can't explain the discrepancy in output between various compile builds.
It could very well be me not getting a grip with git who knows?

It does seem odd, declaring a temp and then storing it in the local and the
only reason I can think of is if EVAL is used on the function and maybe an
exception
is raised?

**Comment by RodneyBates** [comment]
This looks the same as what I got from 5.8.6.

On 3/20/21 2:28 AM, peter mckinna wrote:
> I checked with my old build which I think was November last year. Pretty
> sure
> it was up to date then
> 
> # AllocateJmpbufs TestIt try_count:0
> -----LINE 15 -----
> -----LINE 20 -----
> start_call_direct p.4 0 Word.8
> call_direct p.4 Word.8
> declare_temp 1 1 Word.8 F v.9
> store v.9 0 Int.64 Word.8
> load v.9 0 Word.8 Int.64
> store v.6 0 Int.64 Word.8
> -----LINE 25 -----
> 
> As you can see the temp is 1 byte in size.
> 
> I can't explain the discrepancy in output between various compile builds.
> It could very well be me not getting a grip with git who knows?
> 
> It does seem odd, declaring a temp and then storing it in the local and the
> only reason I can think of is if EVAL is used on the function and maybe an
> exception
> is raised?

I think the llvm code that fails to type-check is because it, sensibly,
is getting the expected type of the call result from the function definition
and the type of the temp to store into from the CG temp, which has now,
sensibly, changed.

I am thinking the thing to do (in the front end) is to make all places use
the cg type (here, Word.8) that corresponds to the high-level type (here CHAR).
This would remove the preexisting inconsistencies and should fix the current
problem too.  It should really be a backend's prerogative to decide to use
a larger size for a function result than absolutely necessary.

I will look into doing that.

> 
> On Sat, 20 Mar 2021 at 06:24, Rodney M. Bates ***@***.***>
> wrote:
> 
>  > I used a 5.8.6 executable compiler (also required a different m3cgcat and
>  > found some differences. I'm not sure what needs to be done, but here's
>  > what is happening:
>  >
>  > On 3/18/21 1:23 AM, peter mckinna wrote:
>  > > Since the packed vars branch was merged I have noticed a slight IR
>  > change to do with temps. I mentioned this
>  > > to Rodney in an email but thought I would produce a small example.
>  > >
>  > > This program
>  > > MODULE Main;
>  > >
>  > > PROCEDURE Test8() : CHAR =
>  > > BEGIN
>  > > RETURN VAL(65,CHAR);
>  > > END Test8;
>  > >
>  > > PROCEDURE TestIt() =
>  > > VAR i8 : CHAR;
>  > > BEGIN
>  > > i8 := Test8();
>  > > END TestIt;
>  > >
>  > > BEGIN
>  > > TestIt();
>  > > END Main.
>  > >
>  > > produces the following (snipped) IR
>  > >
>  > > ...
>  > > declare_procedure Main__Test8 0 Word.8 0 0 F * p.4 <----- declared
>  > return type Word.8 ie 8 bit Word
>  >
>  > Noted.
>  >
>  > > declare_local _result 1 1 Word.8 1457612899 F F 50 v.4 <---- result type
>  > Word.8 not used
>  > > declare_procedure Main__TestIt 0 Void 0 0 F * p.5
>  > > declare_local i8 1 1 Word.8 1457612899 F F 50 v.5
>  > > # Test8
>  > > -----LINE 3 -----
>  > > begin_procedure p.4though possibly in
significantly different ways

**Comment by RodneyBates** [comment]
On 3/20/21 11:25 AM, Rodney M. Bates wrote:
> This looks the same as what I got from 5.8.6.
> 
> On 3/20/21 2:28 AM, peter mckinna wrote:
>> I checked with my old build which I think was November last year. Pretty
>> sure
>> it was up to date then
>>
>> # AllocateJmpbufs TestIt try_count:0
>> -----LINE 15 -----
>> -----LINE 20 -----
>> start_call_direct p.4 0 Word.8
>> call_direct p.4 Word.8
>> declare_temp 1 1 Word.8 F v.9
>> store v.9 0 Int.64 Word.8
>> load v.9 0 Word.8 Int.64
>> store v.6 0 Int.64 Word.8
>> -----LINE 25 -----
>>
>> As you can see the temp is 1 byte in size.
>>
>> I can't explain the discrepancy in output between various compile builds.
>> It could very well be me not getting a grip with git who knows?
>>
>> It does seem odd, declaring a temp and then storing it in the local and the
>> only reason I can think of is if EVAL is used on the function and maybe an
>> exception
>> is raised?
> 
> I think the llvm code that fails to type-check is because it, sensibly,
> is getting the expected type of the call result from the function definition
> and the type of the temp to store into from the CG temp, which has now,
> sensibly, changed.
> 
> I am thinking the thing to do (in the front end) is to make all places use
> the cg type (here, Word.8) that corresponds to the high-level type (here CHAR).
> This would remove the preexisting inconsistencies and should fix the current
> problem too.  It should really be a backend's prerogative to decide to use
> a larger size for a function result than absolutely necessary.

Well, that's pretty much a nonstarter.  The front end has, for each CG type,
a memory type and a stack type.  I uses the latter for everything the goes on
its stack.  It's always full word in size.  So that would upset lots of apple
carts.

The change from earlier is actually a bug fix, although it exposed another
bug.  I could unfix it for now, relatively easily.

The right fix is for the llvm back end to use the stack type in the llvm
call instruction.  But it's not immediately obvious where it can get that.
probably the start_call_direct and call_direct (and, no doubt, the indirect
counterparts) to provide it.  But changing that could really torpedo a lot
of existing stuff, I fear.

**Comment by RodneyBates** [comment]
I'm not sure what needs to be done here.  In the front end, everything has a
memory type and a stack type, the latter full length word sized.  And almost
everything that goes in the abstract stack of the IR had stack type, except
for function results.  The relevant change is that I consistified this.

But the IR operators all have a type for their operands, including those on
the stack.  Apparently, at least for function results, the type need not be
full word.

The llvm failure seems to be because it is getting the type from the declare_procedure
or such.  This is the memory type, and probably needs to stay that way for
debugging and other purposes.  But I don't see where the llvm back end could
get the stack type anyway.

I could just put it back the way it was, just for function results.  Not very
satisfying, but it would not risk requiring pervasive changes.

**Comment by demoitem** [comment]
I tried - just for the hell of it - adding a test in store (of the temp) of
the size of the value
on the stack against the size of the destination type and, if smaller,
do a unilateral zero extend. It worked for some cases but failed p041
and the problem is, as you say, that with the value on the stack, we don't
have info about whether
it's signed or unsigned. One really needs to check the type to do the
correct extend. So that didn't work.

I don't think there's a workaround on the backend side and the fix resides
in m3front.
So llvm is broken at the moment, not just from this, but a couple of other
things. Have you
checked that copy size problem I raised an issue about? Also code issued
after an abort, (although
I might have a workaround for that one, just delete all instructions from
the abort to the end of the
basic block.)

LLVM are about to release version 12 so I've got a new version to post to
github. It's got
a number of fixes and enhancements. I think I will retire the 3.6 and 5
versions at the same time.
I was thinking release a new version for every third or fourth LLVM version.

The good news is I have finally landed a patch on llvm that allows
debugging of sets. Yay! It has been
a drawn-out ordeal getting it through their testing regime, let me tell
you. I have another ready to go
which might cause some ructions. It adds another couple of overloaded
functions (to the 6 or so already there) in DIBuilder
to allow us to debug subranges properly, not to mention dynamic arrays. I
think they really
messed up subranges with their C++ centric view of the world.

Onward, as they say.

**Comment by RodneyBates** [comment]
On 3/30/21 7:41 PM, peter mckinna wrote:
> I tried - just for the hell of it - adding a test in store (of the temp) of
> the size of the value
> on the stack against the size of the destination type and, if smaller,
> do a unilateral zero extend. It worked for some cases but failed p041
> and the problem is, as you say, that with the value on the stack, we don't
> have info about whether
> it's signed or unsigned. One really needs to check the type to do the
> correct extend. So that didn't work.

But.. while the stack types in the IR are all full-word sized, they do distinguish
signed/unsigned/address/floating.

> 
> I don't think there's a workaround on the backend side and the fix resides
> in m3front.

Yes, if I figure out what to emit.

> So llvm is broken at the moment, not just from this, but a couple of other
> things. Have you
> checked that copy size problem I raised an issue about? Also code issued
> after an abort, (although
> I might have a workaround for that one, just delete all instructions from
> the abort to the end of the
> basic block.)

I undertook to not emit unreachable code after abort, but in some cases,
it was harder to decide how far to go than I wanted to do at the time.
This can be improved.  But Jay has complained, if I understand correctly,
that some places where it is gone make it harder to construct legal C.

> 
> LLVM are about to release version 12 so I've got a new version to post to
> github. It's got
> a number of fixes and enhancements. I think I will retire the 3.6 and 5
> versions at the same time.
> I was thinking release a new version for every third or fourth LLVM version.
> 
> The good news is I have finally landed a patch on llvm that allows
> debugging of sets. Yay! It has been
> a drawn-out ordeal getting it through their testing regime, let me tell
> you. I have another ready to go
> which might cause some ructions. It adds another couple of overloaded
> functions (to the 6 or so already there) in DIBuilder
> to allow us to debug subranges properly, not to mention dynamic arrays. I
> think they really
> messed up subranges with their C++ centric view of the world.

That is very good news.  Maybe there is hope for dwarf debugging of
M3 code.

**Comment by demoitem** [comment]
Rodney,

I am going to take back what I said about there not being a workaround for
the temp size problem. I added a small 3 line snippet in call_direct and
call_indirect
that seems to properly extend the return value of small scalars to word
size,
taking proper account of signedness, and it passes all tests.

You say you know what to emit so I'll leave it up to you whether you wish
to
keep your change.

**Comment by demoitem** [comment]
Sorry, missed a crucial 'if'.

So dont bother looking any further. It's all good.

**Comment by RodneyBates** [comment]
On 4/1/21 6:29 PM, peter mckinna wrote:
> Rodney,
> 
> I am going to take back what I said about there not being a workaround for
> the temp size problem. I added a small 3 line snippet in call_direct and
> call_indirect
> that seems to properly extend the return value of small scalars to word
> size,
> taking proper account of signedness, and it passes all tests.
> 
> You say you know what to emit so I'll leave it up to you whether you wish
> to
> keep your change.

OK, L'll leave it as is.  It is more consistent with other things, and is
a bit more efficient code, if translated naively.
