### ISSUE TITLE
CG error with array of packed type

### ISSUE THREAD

**Issue by demoitem** [modula3/cm3#57]
These types

TYPE
  XX = BITS 6 FOR [0..5];
  YY = ARRAY [2..7] OF XX;

generate an error in the front end

new source -> compiling Main.m3
"../src/Main.m3", line 45: ** INTERNAL CG ERROR *** unable to find integer type?  type=Word.64  size/offset/align=6/6/8
1 error encountered

**Comment by RodneyBates** [comment]
On 12/06/2019 06:42 PM, peter mckinna wrote:
> TYPE
> XX = BITS 6 FOR [0..5];
> YY = ARRAY [2..7] OF XX;
> 

What compiler version are you using?  I have been working on this and related failures
in branch packedVars.  I can't reproduce this using that compiler, on AMD64_LINUX.
Right now, the only master branch compiler I have works too.

I would expect this to fail this way with the master branch and a 32-bit machine.
With the packedVars branch and a 32-bit machine, I would expect a compile time
error message instead.  This would be entirely reasonable, because one of the
array elements would cross a 32-bit word boundary.  Smilarly for a record
with 6 fields of 6 bits each.

I also think a 64-bit master branch compiler would probably get the CG failure,
but I might have gotten that fix into master.

I'll try to get some other compiler variants to try it on.

**Comment by demoitem** [comment]
It's AMD64_LINUX master branch. I upgraded the compiler to check with same
result.

Peter

**Comment by RodneyBates** [comment]
So that means the compiler I have that I thought is a master compiler
is not.  Otherwise, all is as I expected.

If you really need this code to work now, you can use the packedVars
branch.  It is probably pretty stable now.  After compiler or library
changes, I always ensure it will recompile itself twice. I will
eventually merge this into master.

**Comment by demoitem** [comment]
Hi Rodney,

  Do you have any plans to merge the packed vars branch into main?

**Comment by RodneyBates** [comment]
Yes, I need to do that.  It's been stable for my uses for some months now.
I think there will be a lot in the master branch that has changed meantime,
so maybe some amount manual merging  will be needed.  I might have to
think to come up with a summary of the things I have done to it.

**Comment by demoitem** [comment]
Fixed
